---
- name: "Apt update"
  shell: "apt-get update -y --force-yes"

- name: "Install system requirements"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- apt_key:
    data: "{{ lookup('file', 'docker-apt-key') }}"
    state: present
  when: internet_available | bool

- name: "Add repository"
  apt_repository:
    repo: 'deb {{ docker_repo }} ubuntu-{{ ansible_distribution_release }} main'
    state: present
  when: internet_available | bool

- name: "Install docker + reqs"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-engine
    - python-docker
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: "Add users to the docker group"
  user:
    name:   "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  with_items: "{{ docker_group_members }}"
  when: docker_group_members is defined

- name: "Create docker client dir"
  file:
    name: "/etc/docker"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: "Deploy Docker client conf"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/docker/{{ item }}"
  with_items:
    - daemon.json

- name: "start docker service"
  service:
    name: docker
    state: restarted
    enabled: yes
  register: service

- name: "wait until docker service is up"
  wait_for:
    path: /var/run/docker.sock
    delay: 10
  when: (service|changed)
